echo "Cleaning previous builds first.."
rm -rf dist
rm -rf build
rm -rf hgboost.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf .pylint.d
rm -rf hgboost/data/*.zip
rm -rf hgboost/data/*.csv
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf hgboost/catboost_info
rm -rf hgboost/docs/catboost_info
rm -rf hgboost/notebooks/catboost_info
rm -rf hgboost/hgboost.egg-info
rm -rf catboost_info
rm -rf hgboost/__pycache__
